### ISSUE TITLE
Conflict with flatly light theme

### ISSUE THREAD

**Issue by PavelBaco** [rgtk/redmine_impersonate#11]
Hi, therre is conflict with flatly light theme, after choose impersonate i have account of user which i select but cant click cancel/storno to ending impersonate, because that banner dont show(or is hidden).

**Comment by nounder** [comment]
What's the exact name of the theme?

**Comment by PavelBaco** [comment]
Its this theme: https://github.com/Nitrino/flatly_light_redmine

**Comment by nounder** [comment]
Unfortunately I cannot afford to support all the themes. This plugin tries to be as generic as possible to work across wide range of themes by using standard Redmine methods for injecting code to the page.

Theme you are using looks very pretty but changes the layout in significant way -- that's why it doesn't work properly.

Feel free to ask theme's author for help or tinker yourself.
